/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@interface MPIncomingCallUtilities : NSObject
{
}

+ (id)wallpaperViewWithImage:(id)arg1;
+ (id)imageForPerson:(void *)arg1 isFullscreen:(char *)arg2;

@end

