/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

#import "SBPluginBundleController-Protocol.h"

@interface MPTelephonyManager : NSObject <SBPluginBundleController>
{
}

+ (id)sharedInstance;
+ (void)awakeFromBundle;
- (id)init;
- (int)callCount;
- (BOOL)activeCallExists;
- (BOOL)heldCallExists;
- (BOOL)incomingCallExists;
- (BOOL)inCall;
- (BOOL)isTTYEnabled;
- (void)displayAlertForCall:(struct __CTCall *)arg1;

@end

